Location.create(address: 'Slavutich arena, Zaporizhya')
Location.create(address: 'Арочный железный мост, Запорожье')
Location.create(address: 'Національний клуб Запорозька Січ, Запорожье')
Location.create(address: 'Парк Дубовая роща, Запорожье')
Location.create(address: 'Парк Победы, Запорожье')
Location.create(address: 'Башня Козлинера, Запорожье')
Location.create(address: 'Запорожский областной краеведческий музей, Запорожье')
Location.create(address: 'Музей о.Хортица, Запорожье')
Location.create(address: 'Запорожский дуб, Запорожье')
Location.create(address: 'Аллея Боевой Славы с горельефом Комбату, Запорожье')
Location.create(address: 'Національний заповідник "Хортиця", Запорожье')
Location.create(address: 'Мосты Преображенского, Запорожье')
Location.create(address: 'Сечевые казаки - театр казацкого боя, Запорожье')
Location.create(address: 'Cooperstown, NY')
Location.create(address: 'Manchester')
Location.create(address: 'Tower Bridge, London')
Location.create(address: 'Greenwich observatory')
Location.create(address: 'Museum of pop culture')
Location.create(address: 'Buckingam Palace')
Location.create(address: 'Pacific Science center')
Location.create(address: 'Eiffel Tower, France')