Location.create(address: 'Cooperstown, NY')
Location.create(address: 'Manchester')
Location.create(address: 'Tower Bridge, London')
Location.create(address: 'Greenwich observatory')
Location.create(address: 'Museum of pop culture')
Location.create(address: 'Buckingam Palace')
Location.create(address: 'Pacific Science center')
Location.create(address: 'Eiffel Tower, France')
Location.create(address: 'Slavutich arena, Zaporizhya')
