50.times do
  Location.create!(address: Faker::Address.unique.street_address)
end
# Location.create(address: 'Cooperstown, NY')
# Location.create(address: 'Manchester')
# Location.create(address: 'Tower Bridge, London')
# Location.create(address: 'Greenwich observatory')
# Location.create(address: 'Museum of pop culture')
# Location.create(address: 'Buckingam Palace')
# Location.create(address: 'Pacific Science center')
# Location.create(address: 'Slavutich arena, Zaporizhya, UA')
# Location.create(address: 'Арочный железный мост, Запорожье')
# Location.create(address: 'Національний клуб Запорозька Січ')
# Location.create(address: 'Національний заповідник "Хортиця"')
# Location.create(address: 'Eiffel Tower, France')